#pragma once

#define EE_HANDS
#define MASTER_LEFT

#define SOFT_SERIAL_PIN D1
#define SELECT_SOFT_SERIAL_SPEED 1

#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT_POLL 10
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_WATCHDOG_TIMEOUT 3000